/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.logitransportes.logic.capaVista.panelesIniciales.administrativos;

import co.logitransportes.logic.capaModelador.Licencias;
import co.logitransportes.logic.capaModelador.Trabajadores;
import co.logitransportes.logic.capaVista.Principal;
import static java.awt.Frame.ICONIFIED;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Camilo y Roberth
 */
public class ClientesJPanel extends javax.swing.JPanel {

    Principal principal;
    private final DefaultTableModel modeloTabla;

    String data[][] = {};
    String headerConductor[] = {"CEDULA", "NOMBRES", "TIPO DE TRABAJADOR", "NUM DE CONTACTO", "ESTADO"};
    private Trabajadores trabajadorEncontrado = null;
    Licencias licenciaEncontrada = null;

    /**
     * Creates new form TrabajadoresJPanel
     */
    public ClientesJPanel(Principal principal) {
        this.principal = principal;
        modeloTabla = new DefaultTableModel(data, headerConductor);

        initComponents();

        jTableDatosEntregas.setModel(modeloTabla);
//        actualizarListaTrabajadoresTODOS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNombresUsuario = new javax.swing.JLabel();
        jLabelBotonAgregarEntrega = new javax.swing.JLabel();
        jLabelTextAgregarEntrega = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatosEntregas = new JTable();
        jPanelInfoEncontrada = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelTextNombres = new javax.swing.JLabel();
        jLabelTextCelular = new javax.swing.JLabel();
        jTextFieldNumLicencia = new javax.swing.JTextField();
        jLabelTextNumLicencia = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jLabelTextCedula = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldUltimoViaje = new javax.swing.JTextField();
        jLabelTextUltimoViaje = new javax.swing.JLabel();
        jLabelTextInfoDelConductor = new javax.swing.JLabel();
        jLabelTextInfoEmpresa = new javax.swing.JLabel();
        jLabelBotonConductor = new javax.swing.JLabel();
        jLabelBotonInfoEmpresa = new javax.swing.JLabel();
        jLabelTextModificarEntrega = new javax.swing.JLabel();
        jLabelTextVerUbi = new javax.swing.JLabel();
        jLabelBotonModificarEntrega = new javax.swing.JLabel();
        jLabelBotonVerUbi = new javax.swing.JLabel();
        jLabelTextInfoEntregas = new javax.swing.JLabel();
        jPanelBusqueda = new javax.swing.JPanel();
        jLabelTextCondicionesBusqueda = new javax.swing.JLabel();
        jTextFieldCondicionBusqueda = new javax.swing.JTextField();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonCompletados = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelBuscar = new javax.swing.JLabel();
        jRadioButtonActivos = new javax.swing.JRadioButton();
        jPanelVentana = new javax.swing.JPanel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 143)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setBackground(new java.awt.Color(0, 50, 168));
        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 50, 168));
        jLabelUsuario.setText("Bienvenido al panel de trabajadores");
        jPanel5.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 245, -1, -1));

        jLabelNombresUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNombresUsuario.setForeground(new java.awt.Color(0, 50, 168));
        jLabelNombresUsuario.setText("Bienvenido al sistema de LogiTransportes\nseñor(a) " + principal.usuario.getIdentificacion().getNombres() + "."
        );
        jPanel5.add(jLabelNombresUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 278, 195, -1));

        jLabelBotonAgregarEntrega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonAgregarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/agregarEntrega.png"))); // NOI18N
        jLabelBotonAgregarEntrega.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonAgregarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabelBotonAgregarEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 140, 50));

        jLabelTextAgregarEntrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTextAgregarEntrega.setText("Confirmar nueva entrega");
        jPanel5.add(jLabelTextAgregarEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/atras.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 30, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Atras");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 143)));

        jTableDatosEntregas.setBackground(new java.awt.Color(207, 216, 220));
        jTableDatosEntregas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableDatosEntregas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableDatosEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIT", "NOMBRE", "NUM CONTACTO", "TEL CONTACTO", "UBICACION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDatosEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDatosEntregasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDatosEntregas);

        jPanelInfoEncontrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfoEncontrada.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfoEncontrada.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfoEncontrada.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 35, 200, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfoEncontrada.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfoEncontrada.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 10));

        jLabelTextNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextNombres.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextNombres.setText("Nombre:");
        jPanelInfoEncontrada.add(jLabelTextNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelTextCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextCelular.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextCelular.setText("No° de celular:");
        jPanelInfoEncontrada.add(jLabelTextCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTextFieldNumLicencia.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldNumLicencia.setBorder(null);
        jPanelInfoEncontrada.add(jTextFieldNumLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 20));

        jLabelTextNumLicencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextNumLicencia.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextNumLicencia.setText("Np° de telefono:");
        jPanelInfoEncontrada.add(jLabelTextNumLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextFieldCedula.setEditable(false);
        jTextFieldCedula.setBorder(null);
        jPanelInfoEncontrada.add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 190, 23));

        jTextFieldNombres.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldNombres.setBorder(null);
        jPanelInfoEncontrada.add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, 20));

        jLabelTextCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextCedula.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextCedula.setText("NIT:");
        jPanelInfoEncontrada.add(jLabelTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jTextFieldCelular.setEditable(false);
        jTextFieldCelular.setBorder(null);
        jTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelularActionPerformed(evt);
            }
        });
        jPanelInfoEncontrada.add(jTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 20));

        jTextFieldUltimoViaje.setEditable(false);
        jTextFieldUltimoViaje.setBorder(null);
        jPanelInfoEncontrada.add(jTextFieldUltimoViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, 20));

        jLabelTextUltimoViaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextUltimoViaje.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextUltimoViaje.setText("Persona contacto:");
        jPanelInfoEncontrada.add(jLabelTextUltimoViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabelTextInfoDelConductor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTextInfoDelConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextInfoDelConductor.setText("Info. del contacto");
        jPanelInfoEncontrada.add(jLabelTextInfoDelConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 110, -1));

        jLabelTextInfoEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTextInfoEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextInfoEmpresa.setText("Info. de contacto");
        jPanelInfoEncontrada.add(jLabelTextInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 120, 20));

        jLabelBotonConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/licenciaConduccionSMALL.png"))); // NOI18N
        jLabelBotonConductor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonConductor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBotonConductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonConductorMouseClicked(evt);
            }
        });
        jPanelInfoEncontrada.add(jLabelBotonConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 110, 50));

        jLabelBotonInfoEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonInfoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/contactoSMALL.png"))); // NOI18N
        jLabelBotonInfoEmpresa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonInfoEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBotonInfoEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonInfoEmpresaMouseClicked(evt);
            }
        });
        jPanelInfoEncontrada.add(jLabelBotonInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, 60));

        jLabelTextModificarEntrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTextModificarEntrega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextModificarEntrega.setText("Modificar datos empresa");
        jPanelInfoEncontrada.add(jLabelTextModificarEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 140, -1));

        jLabelTextVerUbi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTextVerUbi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextVerUbi.setText("Ver ubicación");
        jPanelInfoEncontrada.add(jLabelTextVerUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 80, 20));

        jLabelBotonModificarEntrega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonModificarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/editarSMALL.png"))); // NOI18N
        jLabelBotonModificarEntrega.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonModificarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBotonModificarEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonModificarEntregaMouseClicked(evt);
            }
        });
        jPanelInfoEncontrada.add(jLabelBotonModificarEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 140, 50));

        jLabelBotonVerUbi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonVerUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/mapa.png"))); // NOI18N
        jLabelBotonVerUbi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonVerUbi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelInfoEncontrada.add(jLabelBotonVerUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 80, 60));

        jLabelTextInfoEntregas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTextInfoEntregas.setForeground(new java.awt.Color(0, 60, 143));
        jLabelTextInfoEntregas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextInfoEntregas.setText("Información de los clientes");

        jPanelBusqueda.setBackground(new java.awt.Color(207, 216, 220));
        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextCondicionesBusqueda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextCondicionesBusqueda.setForeground(new java.awt.Color(0, 60, 143));
        jLabelTextCondicionesBusqueda.setText("Condiciones de busqueda:");
        jPanelBusqueda.add(jLabelTextCondicionesBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 30));

        jTextFieldCondicionBusqueda.setBackground(new java.awt.Color(207, 216, 220));
        jTextFieldCondicionBusqueda.setToolTipText("Solo se puede realizar la busqueda por medio del ID.");
        jTextFieldCondicionBusqueda.setBorder(null);
        jPanelBusqueda.add(jTextFieldCondicionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 260, 30));

        jRadioButtonTodos.setBackground(new java.awt.Color(207, 216, 220));
        jRadioButtonTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonTodos.setText("Todos");
        jRadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTodosActionPerformed(evt);
            }
        });
        jPanelBusqueda.add(jRadioButtonTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jRadioButtonCompletados.setBackground(new java.awt.Color(207, 216, 220));
        jRadioButtonCompletados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonCompletados.setText("Conductores");
        jRadioButtonCompletados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompletadosActionPerformed(evt);
            }
        });
        jPanelBusqueda.add(jRadioButtonCompletados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBusqueda.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 260, 10));

        jLabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/buscar.png"))); // NOI18N
        jLabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscarMouseClicked(evt);
            }
        });
        jPanelBusqueda.add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 48, 48));

        jRadioButtonActivos.setBackground(new java.awt.Color(207, 216, 220));
        jRadioButtonActivos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonActivos.setText("Administrativos");
        jPanelBusqueda.add(jRadioButtonActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));

        jLabelMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelMinimizar.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/minimizar.png"))); // NOI18N
        jLabelMinimizar.setToolTipText("Minimizar ventana");
        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMinimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabelMinimizarFocusGained(evt);
            }
        });
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });

        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/cerrar.png"))); // NOI18N
        jLabelCerrar.setToolTipText("Cerrar ventana");
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentanaLayout = new javax.swing.GroupLayout(jPanelVentana);
        jPanelVentana.setLayout(jPanelVentanaLayout);
        jPanelVentanaLayout.setHorizontalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaLayout.createSequentialGroup()
                .addComponent(jLabelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        jPanelVentanaLayout.setVerticalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            .addComponent(jLabelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTextInfoEntregas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelInfoEncontrada, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabelTextInfoEntregas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfoEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
//        principal.volverAInicioTrabajador(this);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jTableDatosEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDatosEntregasMouseClicked
//        obtenerDatosSeleccionado();
    }//GEN-LAST:event_jTableDatosEntregasMouseClicked

    private void jTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelularActionPerformed

    private void jLabelBotonConductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonConductorMouseClicked
//        JOptionPane.showMessageDialog(null, "Licencia\n"
//                + "N° de licencia: " + trabajadorEncontrado.getNumeroLicencia().getNumeroLicencia()
//                + "\nFecha de vencimiento: " + trabajadorEncontrado.getNumeroLicencia().getVigencia()
//                + "\nCategorias: " + trabajadorEncontrado.getNumeroLicencia().getCategorias()
//        );
    }//GEN-LAST:event_jLabelBotonConductorMouseClicked

    private void jLabelBotonInfoEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonInfoEmpresaMouseClicked
//        JOptionPane.showMessageDialog(null, "Info de contacto\n"
//                + "Num de contacto (Celular): " + trabajadorEncontrado.getCedula().getCelularContacto()
//                + "\nNum de contacto (Telefono): " + trabajadorEncontrado.getCedula().getTelefonoContacto()
//                + "\nCONTACTO DE REFERENCIA: "
//                + "\nNombres del contacto: " + trabajadorEncontrado.getNombresContacto()
//                + "\nNum de contacto (Celular): " + trabajadorEncontrado.getNumeroContacto()
//        );
    }//GEN-LAST:event_jLabelBotonInfoEmpresaMouseClicked

    private void jLabelBotonModificarEntregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonModificarEntregaMouseClicked
//        Trabajadores trabajadorBuscado = principal.fachadaTrabajador.buscarTrabajador(Integer.parseInt(jTextFieldConductor.getText()));
//        if (trabajadorBuscado != null) {
//            Entregas entregaEditada = new Entregas(entregaEncontrada.getIdEntrega(), entregaEncontrada.getFecha(), entregaEncontrada.getEstado(), entregaEncontrada.getEstadoIntegridad(), trabajadorBuscado, entregaEncontrada.getEmpresaNit());
//            principal.fachadaEntrega.editarEntregas(entregaEncontrada);
//        } else {
//            JOptionPane.showMessageDialog(null, "No se encontro a la persona con la cedula " + jTextFieldConductor.getText());
//        }
    }//GEN-LAST:event_jLabelBotonModificarEntregaMouseClicked

    private void jRadioButtonCompletadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompletadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCompletadosActionPerformed

    private void jLabelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscarMouseClicked
//        String datoABuscar = jTextFieldCondicionBusqueda.getText();
//        if (datoABuscar.equalsIgnoreCase("") || datoABuscar.equalsIgnoreCase(" ")) {
//            /*if (jRadioButtonTodos.isSelected()) {
//                actualizarListaTrabajadoresTodos("Todos");
//            } else if (jRadioButtonAdministrativos.isSelected()) {
//                actualizarListaTrabajadoresTodos("Administrativo");
//            } else if (jRadioButtonConductor.isSelected()) {
//                actualizarListaTrabajadoresTodos("Conductor");
//            } else if (true) {
//
//            }*/
//        } else {
//            //ASqui se realiza la busqueda
//            Long busqueda = Long.parseLong(datoABuscar);
//            Entregas entregaHallada = principal.fachadaEntrega.buscarEntrega(busqueda);
//            if (entregaHallada != null) {
//                actualizarListaAdministrativos(entregaHallada);
//            } else {
//                JOptionPane.showMessageDialog(null, "No se encontro la entrega con el ID " + busqueda + ".");
//            }
//        }
    }//GEN-LAST:event_jLabelBuscarMouseClicked

    private void jLabelMinimizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelMinimizarFocusGained

    }//GEN-LAST:event_jLabelMinimizarFocusGained

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jRadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTodosActionPerformed
//        if (jRadioButtonTodos.isSelected()) {
//            jRadioButtonActivos.setSelected(false);
//            jRadioButtonCompletados.setSelected(false);
//            actualizarListaTrabajadoresTODOS();
//        } else if (jRadioButtonActivos.isSelected()) {
//            jRadioButtonTodos.setSelected(false);
//            jRadioButtonCompletados.setSelected(false);
//            actualizarListaTrabajadoresADMINISTRATIVOS();
//        } else if (jRadioButtonCompletados.isSelected()) {
//            jRadioButtonTodos.setSelected(false);
//            jRadioButtonActivos.setSelected(false);
//            actualizarListaTrabajadoresCONDUCTORES();
//        }
    }//GEN-LAST:event_jRadioButtonTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabelBotonAgregarEntrega;
    private javax.swing.JLabel jLabelBotonConductor;
    private javax.swing.JLabel jLabelBotonInfoEmpresa;
    private javax.swing.JLabel jLabelBotonModificarEntrega;
    private javax.swing.JLabel jLabelBotonVerUbi;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelNombresUsuario;
    private javax.swing.JLabel jLabelTextAgregarEntrega;
    private javax.swing.JLabel jLabelTextCedula;
    private javax.swing.JLabel jLabelTextCelular;
    private javax.swing.JLabel jLabelTextCondicionesBusqueda;
    private javax.swing.JLabel jLabelTextInfoDelConductor;
    private javax.swing.JLabel jLabelTextInfoEmpresa;
    private javax.swing.JLabel jLabelTextInfoEntregas;
    private javax.swing.JLabel jLabelTextModificarEntrega;
    private javax.swing.JLabel jLabelTextNombres;
    private javax.swing.JLabel jLabelTextNumLicencia;
    private javax.swing.JLabel jLabelTextUltimoViaje;
    private javax.swing.JLabel jLabelTextVerUbi;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelInfoEncontrada;
    private javax.swing.JPanel jPanelVentana;
    private javax.swing.JRadioButton jRadioButtonActivos;
    private javax.swing.JRadioButton jRadioButtonCompletados;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTableDatosEntregas;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCondicionBusqueda;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldNumLicencia;
    private javax.swing.JTextField jTextFieldUltimoViaje;
    // End of variables declaration//GEN-END:variables

//    private void actualizarListaTrabajadoresTODOS() {
//        List<Trabajadores> lc = principal.fachadaTrabajador.listaTrabajadores();
//        imprimirEnTabla(lc);
//    }
//
//    private void actualizarListaTrabajadoresCONDUCTORES() {
//        List<Trabajadores> lc = principal.fachadaTrabajador.listaConductores("Conductor");
//        imprimirEnTabla(lc);
//    }
//
//    private void actualizarListaTrabajadoresADMINISTRATIVOS() {
//        List<Trabajadores> lc = principal.fachadaTrabajador.listaConductores("Administrativo");
//        imprimirEnTabla(lc);
//    }
//
//    private void obtenerDatosSeleccionado() {
//        // Obtenemos el primer dato del renglon seleccionado
//        if (jTableDatosEntregas.getSelectedRow() != -1) {
//            //Obtiene cedula
//            String cedula = (String) modeloTabla.getValueAt(jTableDatosEntregas.getSelectedRow(), 0);
//
//            //Se busca la cedula en la base de datos
//            trabajadorEncontrado = principal.fachadaTrabajador.buscarTrabajador(Long.parseLong(cedula));
//
//            jTextFieldCedula.setText(String.valueOf(trabajadorEncontrado.getCedula().getCedula()));
//            jTextFieldNombres.setText(String.valueOf(trabajadorEncontrado.getCedula().getNombres() + " " + trabajadorEncontrado.getCedula().getApellidos()));
//            jTextFieldCelular.setText(String.valueOf(trabajadorEncontrado.getCedula().getCelularContacto()));
//
////            trabajadorEncontrado = principal.fachadaPersona.buscarPersona(trabajadorEncontrado.getTrabajadorCedula().getCedula());
//            licenciaEncontrada = principal.fachadaLicencia.buscarLicencia(trabajadorEncontrado.getNumeroLicencia().getNumeroLicencia());
//
////empresaEncontrada = principal.fachadaEmpresa.buscarEmpresa(trabajadorEncontrado.getEmpresaNit().getNit());
//            jTextFieldNumLicencia.setText(licenciaEncontrada.getNumeroLicencia().toString());
//
//            jTextFieldUltimoViaje.setText(trabajadorEncontrado.getFechaUltimoViaje().toLocaleString());
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Seleccione un renglon primero.");
//        }
//    }
//
//    private void actualizarListaBuscado(Trabajadores trabajadorHallado) {
//        modeloTabla.setRowCount(0);
//        String[] d = {trabajadorHallado.getCedula().toString(),
//            trabajadorHallado.getPersonas().getNombres() + " " + trabajadorHallado.getPersonas().getApellidos(),
//            trabajadorHallado.getTipoTrabajador(),
//            trabajadorHallado.getPersonas().getCelularContacto().toString(),
//            trabajadorHallado.getEstado() + ""
//        };
//        modeloTabla.addRow(d);
//    }
//
//    private void imprimirEnTabla(List<Trabajadores> listaDeTrabajadores) {
//        if (!listaDeTrabajadores.isEmpty()) {
//            modeloTabla.setRowCount(0);
//            for (int i = 0; i < listaDeTrabajadores.size(); i++) {
//                Trabajadores aux = listaDeTrabajadores.get(i);
//                String[] d = {
//                    aux.getCedula().getCedula().toString(),
//                    aux.getCedula().getNombres() + " " + aux.getCedula().getApellidos(),
//                    aux.getTipoTrabajador(),
//                    aux.getCedula().getCelularContacto().toString(),
//                    aux.getEstado() + ""
//                };
//                modeloTabla.addRow(d);
//            }
//        }
//    }
//}
}