/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.logitransportes.logic.capaVista;

import AppPackage.AnimationClass;
import co.logitransportes.logic.capaModelador.Empresas;
import co.logitransportes.logic.capaModelador.Entregas;
import co.logitransportes.logic.capaModelador.Personas;
import co.logitransportes.logic.capaModelador.Trabajadores;
import co.logitransportes.logic.capaModelador.Usuarios;

import static java.awt.Frame.ICONIFIED;
import java.io.UnsupportedEncodingException;
import java.sql.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Camilo y Roberth
 */
public class InicioJPanel extends javax.swing.JPanel {

    Principal principal;

    private Entregas entregaEncontrada = null;
    Personas personaEncontrada = null;
    Empresas empresaEncontrada = null;

    /**
     * Creates new form n1
     */
    public InicioJPanel(Principal principal) {
        this.principal = principal;

        initComponents();

        iniciarBotones(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.z
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabelTextoBienvenida = new javax.swing.JLabel();
        jLabelTextoEntregasActivas = new javax.swing.JLabel();
        jLabelBotonEntregas = new javax.swing.JLabel();
        jLabelBotonTrabajadores = new javax.swing.JLabel();
        jLabelBotonClientes = new javax.swing.JLabel();
        jLabelBotonEntregasActivas = new javax.swing.JLabel();
        jLabelTextoEntregas = new javax.swing.JLabel();
        jLabelTextoTrabajadores = new javax.swing.JLabel();
        jLabelTextoClientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelVentana = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelMinimizar = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextoBienvenida.setForeground(new java.awt.Color(0, 50, 168));
        jPanel5.add(jLabelTextoBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 280, 20));

        jLabelTextoEntregasActivas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextoEntregasActivas.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextoEntregasActivas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEntregasActivas.setText("Entregas activas");
        jPanel5.add(jLabelTextoEntregasActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 110, 20));

        jLabelBotonEntregas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/envio (1).png"))); // NOI18N
        jLabelBotonEntregas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonEntregas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonEntregas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBotonEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonEntregasMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelBotonEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, 90));

        jLabelBotonTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/equipo.png"))); // NOI18N
        jLabelBotonTrabajadores.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonTrabajadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonTrabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBotonTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonTrabajadoresMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelBotonTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, 90));

        jLabelBotonClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/valor.png"))); // NOI18N
        jLabelBotonClientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabelBotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, 90));

        jLabelBotonEntregasActivas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBotonEntregasActivas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/atras-en-el-tiempo.png"))); // NOI18N
        jLabelBotonEntregasActivas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelBotonEntregasActivas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelBotonEntregasActivas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabelBotonEntregasActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, 90));

        jLabelTextoEntregas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextoEntregas.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextoEntregas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEntregas.setText("Entregas");
        jPanel5.add(jLabelTextoEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 20));

        jLabelTextoTrabajadores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextoTrabajadores.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextoTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoTrabajadores.setText("Trabajadores");
        jPanel5.add(jLabelTextoTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 110, 20));

        jLabelTextoClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextoClientes.setForeground(new java.awt.Color(0, 50, 168));
        jLabelTextoClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoClientes.setText("Clientes");
        jPanel5.add(jLabelTextoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 110, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú principal");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelVentanaLayout = new javax.swing.GroupLayout(jPanelVentana);
        jPanelVentana.setLayout(jPanelVentanaLayout);
        jPanelVentanaLayout.setHorizontalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanelVentanaLayout.setVerticalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel5.add(jPanelVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/cerrar.png"))); // NOI18N
        jLabelCerrar.setToolTipText("Cerrar ventana");
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 27));

        jLabelMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelMinimizar.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/minimizar.png"))); // NOI18N
        jLabelMinimizar.setToolTipText("Minimizar ventana");
        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMinimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabelMinimizarFocusGained(evt);
            }
        });
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });
        jPanel5.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 42, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBotonEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonEntregasMouseClicked
        principal.irAEntregas(this);
        cargarEntregas();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelBotonEntregasMouseClicked

    private void jLabelMinimizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelMinimizarFocusGained

    }//GEN-LAST:event_jLabelMinimizarFocusGained

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabelBotonTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonTrabajadoresMouseClicked
        principal.irATrabajador(this);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelBotonTrabajadoresMouseClicked
//    AnimationClass paneles = new AnimationClass();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBotonClientes;
    private javax.swing.JLabel jLabelBotonEntregas;
    private javax.swing.JLabel jLabelBotonEntregasActivas;
    private javax.swing.JLabel jLabelBotonTrabajadores;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelTextoBienvenida;
    private javax.swing.JLabel jLabelTextoClientes;
    private javax.swing.JLabel jLabelTextoEntregas;
    private javax.swing.JLabel jLabelTextoEntregasActivas;
    private javax.swing.JLabel jLabelTextoTrabajadores;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelVentana;
    // End of variables declaration//GEN-END:variables
    AnimationClass paneles = new AnimationClass(); //Hacia arriba
//        paneles.jLabelYDown(-50, 40, WIDTH, HEIGHT, jLabelTextoBienvenida);
//        
//        paneles.jLabelYUp(580, 82, WIDTH, HEIGHT, jLabelEntregas);
//        paneles.jLabelYUp(580, 82, WIDTH, HEIGHT, jLabelClientes);
//        paneles.jLabelYUp(580, 82, WIDTH, HEIGHT, jLabelNotas);
//        paneles.jLabelYUp(736, 238, WIDTH, HEIGHT, jLabelTextoEntrega);
//        paneles.jLabelYUp(736, 238, WIDTH, HEIGHT, jLabelTextoClientes);
//        paneles.jLabelYUp(736, 238, WIDTH, HEIGHT, jLabelTextoNotas);
//        
//        paneles.jLabelYUp(793, 295, WIDTH, HEIGHT, jLabelTrabajadores);
//        paneles.jLabelYUp(793, 295, WIDTH, HEIGHT, jLabelEntregasActivas);
//        paneles.jLabelYUp(793, 295, WIDTH, HEIGHT, jLabelEditarDatosPersonales);
//        
//        paneles.jLabelYUp(949, 451, WIDTH, HEIGHT, jLabelTextoTrabajadores);
//        paneles.jLabelYUp(949, 451, WIDTH, HEIGHT, jLabelTextoEntregasProgreso);
//        paneles.jLabelYUp(949, 451, WIDTH, HEIGHT, jLabelTextoEditarPersonales);

    public void desplegarMenuAdministrativo() {
//        //Hacia arriba
//        paneles.jLabelYDown(-50, 40, WIDTH, HEIGHT, jLabelTextoBienvenida);
//        
//        paneles.jLabelYUp(580, 82, WIDTH, HEIGHT, jLabelEntregas);
//        paneles.jLabelYUp(580, 82, WIDTH, HEIGHT, jLabelClientes);
//        paneles.jLabelYUp(580, 82, WIDTH, HEIGHT, jLabelNotas);
//        paneles.jLabelYUp(736, 238, WIDTH, HEIGHT, jLabelTextoEntrega);
//        paneles.jLabelYUp(736, 238, WIDTH, HEIGHT, jLabelTextoClientes);
//        paneles.jLabelYUp(736, 238, WIDTH, HEIGHT, jLabelTextoNotas);
//        
//        paneles.jLabelYUp(793, 295, WIDTH, HEIGHT, jLabelTrabajadores);
//        paneles.jLabelYUp(793, 295, WIDTH, HEIGHT, jLabelEntregasActivas);
//        paneles.jLabelYUp(793, 295, WIDTH, HEIGHT, jLabelEditarDatosPersonales);
//        
//        paneles.jLabelYUp(949, 451, WIDTH, HEIGHT, jLabelTextoTrabajadores);
//        paneles.jLabelYUp(949, 451, WIDTH, HEIGHT, jLabelTextoEntregasProgreso);
//        paneles.jLabelYUp(949, 451, WIDTH, HEIGHT, jLabelTextoEditarPersonales);
    }
//
//    public void desplegarMenuCliente() {
//        //Hacia arriba
//        paneles.jLabelYDown(-50, 40, WIDTH, HEIGHT, jLabelTextoBienvenida);
//
//        paneles.jLabelYUp(588, 90, WIDTH, HEIGHT, jLabelSolicitarServicio);
//        paneles.jLabelYUp(588, 90, WIDTH, HEIGHT, jLabelBuscarUbicacion);
//
//        paneles.jLabelYUp(748, 250, WIDTH, HEIGHT, jLabelTextoSolicitarServicio);
//        paneles.jLabelYUp(818, 250, WIDTH, HEIGHT, jLabelTextoUbicacion);
//
//        paneles.jLabelYUp(978, 320, WIDTH, HEIGHT, jLabelHistorial);
//        paneles.jLabelYUp(818, 320, WIDTH, HEIGHT, jLabelContacto);
//
//        paneles.jLabelYUp(978, 480, WIDTH, HEIGHT, jLabelTextoHistorial);
//        paneles.jLabelYUp(978, 480, WIDTH, HEIGHT, jLabelTextoContacto);
//    }

    private void iniciarBotones(boolean real) {
        jLabelBotonEntregas.setVisible(real);
        jLabelTextoEntregas.setVisible(real);
        jLabelBotonTrabajadores.setVisible(real);
        jLabelTextoTrabajadores.setVisible(real);
        jLabelBotonClientes.setVisible(real);
        jLabelTextoClientes.setVisible(real);
        jLabelBotonEntregasActivas.setVisible(real);
        jLabelTextoEntregasActivas.setVisible(real);
    }

    private void cargarEntregas() {

    }

}
