/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.logitransportes.logic.capaVista;

import static java.awt.Frame.ICONIFIED;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Camilo y Roberth
 */
public class InicioSesionJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form InicioSesionJPanel
     */
    public InicioSesionJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelLogoUsuarioPequeño = new javax.swing.JLabel();
        jLabelVerContra = new javax.swing.JLabel();
        jLabelLogoContraseniaPequenio = new javax.swing.JLabel();
        jLabelIniciarSesión = new javax.swing.JLabel();
        jPanelVentana = new javax.swing.JPanel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/usuarioBIG.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/logo_banner.png"))); // NOI18N

        jLabelUsuario.setBackground(new java.awt.Color(0, 50, 168));
        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 50, 168));
        jLabelUsuario.setText("Usuario:");

        jLabelContrasenia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContrasenia.setForeground(new java.awt.Color(0, 50, 168));
        jLabelContrasenia.setText("Contraseña:");

        jTextFieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUsuario.setBorder(null);

        jPasswordFieldContrasenia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordFieldContrasenia.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabelLogoUsuarioPequeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/usuarioSMALL.png"))); // NOI18N

        jLabelVerContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/verContra.png"))); // NOI18N
        jLabelVerContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVerContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVerContraMouseClicked(evt);
            }
        });

        jLabelLogoContraseniaPequenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/clave.png"))); // NOI18N

        jLabelIniciarSesión.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIniciarSesión.setForeground(new java.awt.Color(0, 50, 168));
        jLabelIniciarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/iniciar-sesionOFF.png"))); // NOI18N
        jLabelIniciarSesión.setText("Iniciar sesión");
        jLabelIniciarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIniciarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIniciarSesiónMouseClicked(evt);
            }
        });

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));

        jLabelMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelMinimizar.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/minimizar.png"))); // NOI18N
        jLabelMinimizar.setToolTipText("Minimizar ventana");
        jLabelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMinimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabelMinimizarFocusGained(evt);
            }
        });
        jLabelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizarMouseClicked(evt);
            }
        });

        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/imagenes/iconos/cerrar.png"))); // NOI18N
        jLabelCerrar.setToolTipText("Cerrar ventana");
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentanaLayout = new javax.swing.GroupLayout(jPanelVentana);
        jPanelVentana.setLayout(jPanelVentanaLayout);
        jPanelVentanaLayout.setHorizontalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaLayout.createSequentialGroup()
                .addComponent(jLabelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        jPanelVentanaLayout.setVerticalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            .addComponent(jLabelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIniciarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabelLogoContraseniaPequenio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jPasswordFieldContrasenia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelUsuario)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabelLogoUsuarioPequeño, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jTextFieldUsuario))
                        .addComponent(jLabelContrasenia)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelUsuario)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoUsuarioPequeño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelContrasenia)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoContraseniaPequenio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIniciarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelVerContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerContraMouseClicked
        //        Boolean realizacion = false;
        //        if (realizacion = true) {
        //            jLabelVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/principal/media/noVer.png"))); // NOI18N
        //            jPasswordFieldContrasenia.setEchoChar((char) 0); // este método es el que hace visible el texto del jPasswordField
        //            realizacion = false;
        //        } else {
        //            jLabelVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/logitransportes/logic/capaVista/principal/media/verContra.png"))); // NOI18N
        //            jPasswordFieldContrasenia.setEchoChar('*');
        //            realizacion = true;
        //        }
    }//GEN-LAST:event_jLabelVerContraMouseClicked

    private void jLabelIniciarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIniciarSesiónMouseClicked
        try {
            String usuario = jTextFieldUsuario.getText();
            String contrasenia = jPasswordFieldContrasenia.getText();

            if (usuario.equals("") || contrasenia.equalsIgnoreCase("") || usuario.equals(" ") || contrasenia.equalsIgnoreCase(" ")) {
                JOptionPane.showMessageDialog(null, "No puede dejer ningun campo vacio.");
            } else {
                if (usuario.contains("@")) {
                    usuario = principal.fachadaCodificacion.codificacion(usuario);
                    contrasenia = principal.fachadaCodificacion.codificacion(contrasenia);
                    System.out.println("correo= " + usuario);
                    System.out.println("contra= " + contrasenia);
                    principal.usuario = principal.fachadaUsuario.buscarUsuario(usuario, "correo");
                } else {
                    usuario = principal.fachadaCodificacion.codificacion(usuario);
                    contrasenia = principal.fachadaCodificacion.codificacion(contrasenia);
                    System.out.println("usua= " + usuario);
                    System.out.println("contra= " + contrasenia);
                    principal.usuario = principal.fachadaUsuario.buscarUsuario(usuario, "nickname");
                }
                if (principal.usuario != null) {
                    if (principal.usuario.getIdentificacion().getEstadoIntegridad() != false && principal.usuario.getContrasenia().equals(contrasenia)) {
                        //          jLabelTextoBienvenida.setText("Bienvenido al sistema de LogiTransportes señor(a) " + principal.usuario.getPersona().getNombres() + ".");
                        principal.trabajador = principal.fachadaTrabajador.buscarTrabajador(principal.usuario.getIdentificacion().getIdentificacion());
                        if (principal.trabajador != null) {
                            //Es trabajador
                            principal.administrativo = principal.fachadaTrabajador.buscarAdministrativo(principal.usuario.getIdentificacion().getIdentificacion());
                            principal.conductor = principal.fachadaTrabajador.buscarConductor(principal.usuario.getIdentificacion().getIdentificacion());
                            if (principal.administrativo != null) {
                                //                System.out.println("es admin");
                                //              desplegarMenuAdministrativo();
                                //            iniciarBotones(true);
                                //          limpiarCasillas();
                                System.out.println("ya");
                                principal.irAPantallaPrincipal(this);
                            } else if (principal.conductor != null) {
                                //FALTA PROGRAMAR
                                System.out.println("d");
                            }
                        } else {
                            //                        Cliente clienteBuscado = principal.gestionClientes.buscarPorCorreo(personaBuscada.getCedula());
                            //
                            //                        if (clienteBuscado != null) {
                            //                            //Es cliente
                            //                            desplegarMenuCliente();
                            //                            limpiarCasillas();
                            //                        }
                            System.out.println("aqui");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Su usuario o contraseña no son correctos.");
                    }

                } else {
                    Integer opcion = JOptionPane.showConfirmDialog(null, "Su usuario no exite.\n¿Desea registrarse en el sistema?");
                    //1= No; 0=Si.
                    if (opcion == 0) {
                        System.out.println("A registrarse");
                    }
                }
            }
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(InicioJPanel.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex2) {

        }
    }//GEN-LAST:event_jLabelIniciarSesiónMouseClicked

    private void jLabelMinimizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelMinimizarFocusGained

    }//GEN-LAST:event_jLabelMinimizarFocusGained

    private void jLabelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizarMouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizarMouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelIniciarSesión;
    private javax.swing.JLabel jLabelLogoContraseniaPequenio;
    private javax.swing.JLabel jLabelLogoUsuarioPequeño;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelVerContra;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelVentana;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
